### generate
POST http://localhost:11434/api/generate HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "model": "llama3",
  "options": {
    "temperature": 0
  },
  "prompt": "Please explain this table schema: CREATE TABLE `album` ( `AlbumId` int(11) NOT NULL, `Title` varchar(160) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL, `ArtistId` int(11) NOT NULL, PRIMARY KEY (`AlbumId`), KEY `IFK_AlbumArtistId` (`ArtistId`), CONSTRAINT `FK_AlbumArtistId` FOREIGN KEY (`ArtistId`) REFERENCES `artist` (`ArtistId`) ON DELETE NO ACTION ON UPDATE NO ACTION ) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci",
  "stream": false
}

### generate
POST http://localhost:11434/api/generate HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "model": "qwen2",
  "options": {
    "temperature": 0
  },
  "prompt": "You are interacting with a user who is asking a question about the company's database. Based on the question below, response it with MySQL Query only, no chit-chat only SQL.\n\nQuestion: How to show my customer's name?",
  "stream": false
}

### chat dengan history
POST http://localhost:11434/api/chat HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "model": "llama3",
  "stream": false,
  "options": {
    "temperature": 0
  },
  "messages": [
    {
      "role": "system",
      "content": "You are interacting with a user who is asking a question about the company's data. Based on the user question below, response it with MySQL Query only, no chit-chat only SQL."
    },
    {
      "role": "user",
      "content": "Tell me some of my customers name."
    }
  ]
}


### chat dengan history
POST http://localhost:11434/api/chat HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "model": "llama3",
  "stream": false,
  "options": {
    "temperature": 1
  },
  "messages": [
    {
      "role": "system",
      "content": "You are Mario from the Super Mario Bros. Answer the user question as Mario."
    },
    {
      "role": "user",
      "content": "do you have sibling?"
    }
  ]
}

### WEB SIMULATION DATABASE - new session
POST http://localhost/php_ollama/app/Router.php?llm=1&topic=database&path=ollama%2Fprompt&sessionId=new&prompt=di+kota+apa+konsumen+kita+paling+banyak+tinggal HTTP/1.1
Accept: text/event-stream

### WEB SIMULATION DATABASE - load session
POST http://localhost/php_ollama/app/Router.php?llm=1&topic=database&path=ollama%2Fprompt&sessionId=2406240942_6678dd10ee0b0&prompt=is+our+office+exists+in+that+city? HTTP/1.1
Accept: text/event-stream

### WEB SIMULATION GENERAL CHAT - new session
POST http://localhost/php_ollama/app/Router.php HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "llm": 0,
  "topic": "general",
  "path": "ollama/prompt",
  "sessionId": "2406180457_66715a1947958",
  "prompt": "Kenapa putri selalu diculik"
}